### ISSUE TITLE
compile on Ubuntu / gcc 4.8.4 gives: Depth/depth.cpp:26:127: error: 'UINT_MAX' was not declared in this scope

### ISSUE THREAD

**Issue by monarc99** [sekrit-twc/zimg#9]
make
  CXX      API/zimg.lo
  CXX      Colorspace/colorspace.lo
  CXX      Colorspace/colorspace_param.lo
  CXX      Colorspace/graph.lo
  CXX      Colorspace/matrix3.lo
  CXX      Colorspace/operation.lo
  CXX      Colorspace/operation_impl.lo
  CXX      Depth/depth_convert.lo
  CXX      Depth/depth.lo
Depth/depth.cpp: In function 'void zimg::depth::{anonymous}::convert_dithered(const zimg::depth::DitherConvert&, const zimg::ImagePlane<const void>&, const zimg::ImagePlane<void>&, void*)':
Depth/depth.cpp:26:127: error: 'UINT_MAX' was not declared in this scope
  LineBuffer<void> src_buf{ (void *)src.data(), (unsigned)src.width(), (unsigned)src.stride() * pixel_size(src.format().type), UINT_MAX };
                                                                                                                               ^
Depth/depth.cpp:26:136: error: no matching function for call to 'zimg::LineBuffer<void>::LineBuffer(<brace-enclosed initializer list>)'
  LineBuffer<void> src_buf{ (void *)src.data(), (unsigned)src.width(), (unsigned)src.stride() * pixel_size(src.format().type), UINT_MAX };
                                                                                                                                        ^
Depth/depth.cpp:26:136: note: candidates are:
In file included from Depth/depth.cpp:4:0:
./Common/linebuffer.h:44:2: note: zimg::LineBuffer<T>::LineBuffer(T*, unsigned int, unsigned int, unsigned int) [with T = void]
  LineBuffer(T *ptr, unsigned width, unsigned byte_stride, unsigned mask) :
  ^
./Common/linebuffer.h:44:2: note:   no known conversion for argument 4 from '<type error>' to 'unsigned int'
./Common/linebuffer.h:34:2: note: zimg::LineBuffer<T>::LineBuffer() [with T = void]
  LineBuffer() = default;
  ^
./Common/linebuffer.h:34:2: note:   candidate expects 0 arguments, 4 provided
./Common/linebuffer.h:18:7: note: constexpr zimg::LineBuffer<void>::LineBuffer(const zimg::LineBuffer<void>&)
 class LineBuffer {
       ^
./Common/linebuffer.h:18:7: note:   candidate expects 1 argument, 4 provided
./Common/linebuffer.h:18:7: note: constexpr zimg::LineBuffer<void>::LineBuffer(zimg::LineBuffer<void>&&)
./Common/linebuffer.h:18:7: note:   candidate expects 1 argument, 4 provided
Depth/depth.cpp:27:128: error: no matching function for call to 'zimg::LineBuffer<void>::LineBuffer(<brace-enclosed initializer list>)'
  LineBuffer<void> dst_buf{ dst.data(), (unsigned)dst.width(), (unsigned)dst.stride() * pixel_size(dst.format().type), UINT_MAX };
                                                                                                                                ^
Depth/depth.cpp:27:128: note: candidates are:
In file included from Depth/depth.cpp:4:0:
./Common/linebuffer.h:44:2: note: zimg::LineBuffer<T>::LineBuffer(T*, unsigned int, unsigned int, unsigned int) [with T = void]
  LineBuffer(T *ptr, unsigned width, unsigned byte_stride, unsigned mask) :
  ^
./Common/linebuffer.h:44:2: note:   no known conversion for argument 4 from '<type error>' to 'unsigned int'
./Common/linebuffer.h:34:2: note: zimg::LineBuffer<T>::LineBuffer() [with T = void]
  LineBuffer() = default;
  ^
./Common/linebuffer.h:34:2: note:   candidate expects 0 arguments, 4 provided
./Common/linebuffer.h:18:7: note: constexpr zimg::LineBuffer<void>::LineBuffer(const zimg::LineBuffer<void>&)
 class LineBuffer {
       ^
./Common/linebuffer.h:18:7: note:   candidate expects 1 argument, 4 provided
./Common/linebuffer.h:18:7: note: constexpr zimg::LineBuffer<void>::LineBuffer(zimg::LineBuffer<void>&&)
./Common/linebuffer.h:18:7: note:   candidate expects 1 argument, 4 provided
make: *** [Depth/depth.lo] Fehler 1

**Comment by sekrit-twc** [comment]
Should be fixed.

**Comment by monarc99** [comment]
thx :+1: perfect
