### ISSUE TITLE
error: use of undeclared identifier '_mm256_cvtph_ps'

### ISSUE THREAD

**Issue by ilovezfs** [sekrit-twc/zimg#52]
zimg 2.2.1 fails to build on macOS <= 10.10

The errors look like this (this is just an excerpt):
```
src/zimg/depth/f16c_ivb.cpp:52:14: error: use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_left - 8)));
                           ^~~~~~~~~~~~~~~
                           _mm256_cvtpd_ps
/usr/bin/../lib/clang/5.1/include/avxintrin.h:528:1: note: '_mm256_cvtpd_ps' declared here
_mm256_cvtpd_ps(__m256d __a)
^
src/zimg/depth/f16c_ivb.cpp:52:30: error: cannot initialize a parameter of type '__m256d' with an rvalue of type '__m128i'
                __m256 x = _mm256_cvtph_ps(_mm_load_si128((const __m128i *)(src_p + vec_left - 8)));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/clang/5.1/include/avxintrin.h:528:25: note: passing argument to parameter '__a' here
_mm256_cvtpd_ps(__m256d __a)
                        ^
```
Here's a full build log: https://gist.github.com/ilovezfs/643b502700507d49eec09ccb3b3ba348

The underlying issue is that https://reviews.llvm.org/rL254528 moved the relevant symbols from `f16cintrin.h` to `immintrin.h`, so earlier versions won't have them defined if only `immintrin.h` is included. If you try to include `f16cintrin.h` directly, the build will complain that `f16cintrin.h` should be included directly, and that instead it should be included indirectly by including `x86intrin.h`.

So for the Homebrew upgrade to 2.2.1 I'm working around the build failure by adding the following to the formula:
```
    if MacOS.version < :el_capitan
      (buildpath/"brew_include/immintrin.h").write <<-EOS.undent
        #include <x86intrin.h>
        #include_next <immintrin.h>
      EOS
      ENV.prepend "CPPFLAGS", "-I#{buildpath}/brew_include"
    end
```

It would be great, though, if there were a proper upstream fix in the zimg source code. Thanks for your help.

Cf.
https://github.com/Homebrew/homebrew-core/pull/4109
(and same problem in 2.2 https://github.com/Homebrew/homebrew-core/pull/3956)

**Comment by sekrit-twc** [comment]
This won't be fixed. Upgrade your CLANG version to 3.8 (XCode 7.3?), so that it will be compatible with ICC/ICL.

**Comment by ilovezfs** [comment]
It's not *my* clang version. I'm one of the Homebrew maintainers, who happened to be updating this software, and our CI failed on 10.9 and 10.10 due to this issue.

I'll interpret your remark above as a request to set a minimum macOS requirement of El Capitan (7.2.1 is the maximum Xcode version that runs on 10.10 Yosemite), which is unfortunate since Apple is still supporting 10.10 at this point and since the fix is trivial.

**Comment by sekrit-twc** [comment]
I thought you discovered a workaround for this issue on your end? You can also configure with "--disable-simd" for a C++-only build.
